### ISSUE TITLE
WebStorm not reloading node_modules/.prisma/client/index.d.ts when client is generated.

### ISSUE THREAD

**Issue by BaptisteMahe** [gabrielcolson/prisma-intellij-plugin#21]
Hello,
First of all, thank you for all the work put into this plugin that gives me a better time working with Prisma on WebStorm.
Maybe this question seems a bit silly and netpicking but as I am working on a quickly developing project running Prisma and it bugs me a lot.

So when using WebStorm I really enjoy the type checking on my queries and as I am running `npx prisma generate` a lot I would like the errors I get in my IDE to follow the recently generated types in my _node_modules/.prisma/client/index.d.ts_. But it seems that I have to restart my IDE to have the fully _dependencies indexing_ to overwrite the types.
- I tried **Mark directory as** > **Not excluded** in the IDE without success.
- Same for adding _node_modules/.prisma_ as **project's library**.

**It may rely on this plugin to do so but: Is there a way for me to force WebStorm to watch my node_modules/.prisma/client/index.d.ts file and reload the types when it's changed?**

**Comment by gabrielcolson** [comment]
Hello @BaptisteMahe !

I have observed this behavior before and what works for me is to run the command "restart typescript server" inside webstorm. I don't think there is another way of doing it and I don't think this plugin can help. Maybe you should try to report this issue to JetBrains.
